/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Fri Mar 03 18:29:40 2017. */

#include "custom.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Custom_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t Custom__Header_fields[5] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, Custom__Header, command, command, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, Custom__Header, originator, command, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, Custom__Header, nestedPath, originator, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, Custom__Header, nestedSpec, nestedPath, 0),
    PB_LAST_FIELD
};

const pb_field_t Custom_Call_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, Custom_Call, phone_number, phone_number, 0),
    PB_LAST_FIELD
};

const pb_field_t Custom_Sms_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, Custom_Sms, phone_number, phone_number, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, Custom_Sms, message, phone_number, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
