/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Fri Mar 03 18:29:40 2017. */

#ifndef PB_CUSTOM_PB_H_INCLUDED
#define PB_CUSTOM_PB_H_INCLUDED
#include "../Protobuf/pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Custom_Command {
    Custom_Command_CALL = 1,
    Custom_Command_SMS = 2
} Custom_Command;
#define _Custom_Command_MIN Custom_Command_CALL
#define _Custom_Command_MAX Custom_Command_SMS
#define _Custom_Command_ARRAYSIZE ((Custom_Command)(Custom_Command_SMS+1))

/* Struct definitions */
typedef struct _Custom {
    char dummy_field;
/* @@protoc_insertion_point(struct:Custom) */
} Custom;

typedef struct _Custom_Call {
    char phone_number[20];
/* @@protoc_insertion_point(struct:Custom_Call) */
} Custom_Call;

typedef struct _Custom_Sms {
    char phone_number[20];
    char message[250];
/* @@protoc_insertion_point(struct:Custom_Sms) */
} Custom_Sms;

typedef struct _Custom__Header {
    Custom_Command command;
    bool has_originator;
    char originator[30];
    bool has_nestedPath;
    char nestedPath[50];
    bool has_nestedSpec;
    char nestedSpec[40];
/* @@protoc_insertion_point(struct:Custom__Header) */
} Custom__Header;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Custom_init_default                      {0}
#define Custom__Header_init_default              {(Custom_Command)0, false, "", false, "", false, ""}
#define Custom_Call_init_default                 {""}
#define Custom_Sms_init_default                  {"", ""}
#define Custom_init_zero                         {0}
#define Custom__Header_init_zero                 {(Custom_Command)0, false, "", false, "", false, ""}
#define Custom_Call_init_zero                    {""}
#define Custom_Sms_init_zero                     {"", ""}

/* Field tags (for use in manual encoding/decoding) */
#define Custom_Call_phone_number_tag             1
#define Custom_Sms_phone_number_tag              1
#define Custom_Sms_message_tag                   2
#define Custom__Header_command_tag               1
#define Custom__Header_originator_tag            2
#define Custom__Header_nestedPath_tag            3
#define Custom__Header_nestedSpec_tag            4

/* Struct field encoding specification for nanopb */
extern const pb_field_t Custom_fields[1];
extern const pb_field_t Custom__Header_fields[5];
extern const pb_field_t Custom_Call_fields[2];
extern const pb_field_t Custom_Sms_fields[3];

/* Maximum encoded size of messages (where known) */
#define Custom_size                              0
#define Custom__Header_size                      128
#define Custom_Call_size                         22
#define Custom_Sms_size                          275

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CUSTOM_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
