/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Tue Sep 27 10:29:54 2016. */

#ifndef PB_CUSTOM_PB_H_INCLUDED
#define PB_CUSTOM_PB_H_INCLUDED
#include "../Protobuf/pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Custom_Command {
    Custom_Command_SERIALPRINTLN = 1,
    Custom_Command_PING = 2,
    Custom_Command_TESTEVENTS = 3
} Custom_Command;
#define _Custom_Command_MIN Custom_Command_SERIALPRINTLN
#define _Custom_Command_MAX Custom_Command_TESTEVENTS
#define _Custom_Command_ARRAYSIZE ((Custom_Command)(Custom_Command_TESTEVENTS+1))

/* Struct definitions */
typedef struct _Custom {
    char dummy_field;
/* @@protoc_insertion_point(struct:Custom) */
} Custom;

typedef struct _Custom_ping {
    char dummy_field;
/* @@protoc_insertion_point(struct:Custom_ping) */
} Custom_ping;

typedef struct _Custom_testEvents {
    char dummy_field;
/* @@protoc_insertion_point(struct:Custom_testEvents) */
} Custom_testEvents;

typedef struct _Custom__Header {
    Custom_Command command;
    bool has_originator;
    char originator[30];
    pb_callback_t nestedPath;
    pb_callback_t nestedSpec;
/* @@protoc_insertion_point(struct:Custom__Header) */
} Custom__Header;

typedef struct _Custom_serialPrintln {
    char message[100];
/* @@protoc_insertion_point(struct:Custom_serialPrintln) */
} Custom_serialPrintln;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Custom_init_default               {0}
#define Custom__Header_init_default       {(Custom_Command)0, false, "", {{NULL}, NULL}, {{NULL}, NULL}}
#define Custom_serialPrintln_init_default {""}
#define Custom_ping_init_default          {0}
#define Custom_testEvents_init_default    {0}
#define Custom_init_zero                  {0}
#define Custom__Header_init_zero          {(Custom_Command)0, false, "", {{NULL}, NULL}, {{NULL}, NULL}}
#define Custom_serialPrintln_init_zero    {""}
#define Custom_ping_init_zero             {0}
#define Custom_testEvents_init_zero       {0}

/* Field tags (for use in manual encoding/decoding) */
#define Custom__Header_command_tag        1
#define Custom__Header_originator_tag     2
#define Custom__Header_nestedPath_tag     3
#define Custom__Header_nestedSpec_tag     4
#define Custom_serialPrintln_message_tag  1

/* Struct field encoding specification for nanopb */
extern const pb_field_t Custom_fields[1];
extern const pb_field_t Custom__Header_fields[5];
extern const pb_field_t Custom_serialPrintln_fields[2];
extern const pb_field_t Custom_ping_fields[1];
extern const pb_field_t Custom_testEvents_fields[1];

/* Maximum encoded size of messages (where known) */
#define Custom_size                       0
/* Custom__Header_size depends on runtime parameters */
#define Custom_serialPrintln_size         102
#define Custom_ping_size                  0
#define Custom_testEvents_size            0

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CUSTOM_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
