/*
 * JsonFileInfoRes.hpp
 *
 *  Created on: Feb 7, 2017
 *      Author: taho
 */

#ifndef CONTROLLER_JSONMESSAGE_JSONFILE_JSONFILEINFORES_HPP_
#define CONTROLLER_JSONMESSAGE_JSONFILE_JSONFILEINFORES_HPP_



#endif /* CONTROLLER_JSONMESSAGE_JSONFILE_JSONFILEINFORES_HPP_ */
